[project]
name = "dhfs"
version = "0.1.0"
description = "Data Hub File Service - a service enabling file inspection and re-encryption at Data Hubs"
dependencies = [
    "typer >= 0.19.1",
    "ghga-service-commons[auth,http,objectstorage,transports] >= 5.0",
    "hexkit[s3] >= 7.0",
    "crypt4gh >= 1.7",
]

[project.urls]
Repository = "https://github.com/ghga-de/datahub-file-service"

[project.scripts]
dhfs = "dhfs.__main__:run"
